# This is a basic workflow to help you get started with Actions
name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Configure Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.18.4'
      
    - name: Install
      run: |
        npm ci
        npm run build
      env:
          DB_NAME: ${{secrets.DB_NAME}}
          DB_PWD: ${{secrets.DB_PWD}}
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
